# Generated by Django 5.1 on 2024-08-23 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=10)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ticket_quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_type', models.CharField(choices=[('Music-event', 'Music'), ('Educational-event', 'Educational'), ('Recreational-event', 'Recreational')], max_length=20)),
                ('event_date', models.DateTimeField()),
                ('event_organiser', models.CharField(max_length=10)),
                ('event_status', models.BooleanField(default=False)),
                ('event_ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_tickets', to='main.tickets')),
            ],
        ),
    ]
