# Generated by Django 5.1 on 2024-08-23 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_events_event_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_ticket',
        ),
        migrations.AddField(
            model_name='tickets',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='main.events'),
        ),
    ]
