# Generated by Django 5.1 on 2024-08-24 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'permissions': [('can_create_event', 'Can create events'), ('can_update_event', 'Can update events'), ('can_delete_event', 'Can delete events'), ('can_read_event', 'Can read events')]},
        ),
        migrations.AlterModelOptions(
            name='tickets',
            options={'permissions': [('can_create_ticket', 'Can create tickets'), ('can_update_ticket', 'Can update tickets'), ('can_delete_ticket', 'Can delete tickets'), ('can_read_ticket', 'Can read tickets')]},
        ),
    ]
