# Generated by Django 5.1 on 2024-08-24 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_events_options_alter_tickets_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_organizer',
        ),
    ]
