# Generated by Django 5.1 on 2024-08-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_events_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_ticket_quantity',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticket_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
