# Generated by Django 5.1 on 2024-08-25 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_events_event_ticket_quantity_alter_tickets_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_organizer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
