# Generated by Django 5.1 on 2024-08-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_tickets_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='ticket_price',
        ),
    ]
