# Generated by Django 5.1 on 2024-08-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_tickets_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='ticket_price',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=8, null=True),
        ),
    ]
